const $ = id => document.getElementById(id);
const state = { city: 'New York', coords: null, metric: false, map: null, overlay: null, layer: 'precipitation_new', apiKey: '' };
const PRODUCTION_API_BASE = 'https://weather-web-jacu.onrender.com';
const API_BASE = window.__API_BASE__ || ((window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1' || window.location.protocol === 'file:') ? 'http://localhost:5000' : PRODUCTION_API_BASE);
const icon = c => /thunder/i.test(c) ? '⛈' : /rain|drizzle/i.test(c) ? '🌧' : /snow/i.test(c) ? '❄' : /cloud/i.test(c) ? '☁' : '☀';
const f = n => state.metric ? `${Math.round(n)}°C` : `${Math.round(n * 9 / 5 + 32)}°F`;
const speed = n => state.metric ? `${Math.round(n * 3.6)} km/h` : `${Math.round(n * 2.237)} mph`;
const time = x => x ? new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(x)) : '—';
async function request(path) { const started = performance.now(); const r = await fetch(API_BASE + path); $('latency').textContent = `${Math.round(performance.now() - started)} ms`; const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || 'Request failed'); return data; }
function healthAdvice(aqi) { if (aqi <= 1) return 'Excellent for outdoor activity.'; if (aqi === 2) return 'Most people can enjoy normal outdoor activity.'; if (aqi === 3) return 'Sensitive groups should consider reducing prolonged outdoor exertion.'; return 'Limit prolonged outdoor exertion, especially for sensitive groups.'; }
function renderCurrent(w) { const t = w.temperature; state.coords = w.location; $('place').textContent = `${w.location.name}${w.location.country ? `, ${w.location.country}` : ''}`; $('temperature').textContent = f(t.celsius); $('condition').textContent = w.condition.description; $('updated').textContent = `Observed ${time(w.observedAt)} · ${w.provider}`; $('hero-icon').textContent = icon(w.condition.main); document.body.className = /rain|storm/i.test(w.condition.main) ? 'rain' : 'clear'; $('feels').textContent = f(t.feelsLikeCelsius); $('humidity').textContent = `${w.humidity}%`; $('wind').textContent = `${speed(w.wind.speedMps)} ${w.wind.direction}${w.wind.gustMps ? ` · gust ${speed(w.wind.gustMps)}` : ''}`; $('uv').textContent = 'Provider unavailable'; $('pressure').textContent = `${w.pressureHpa} hPa`; $('visibility').textContent = w.visibilityMeters == null ? '—' : `${(w.visibilityMeters / 1000).toFixed(1)} km`; $('dew').textContent = f(w.dewPointCelsius); $('sun').textContent = `${time(w.sun.sunrise)} / ${time(w.sun.sunset)}`; }
function renderForecast(data) { $('hourly').innerHTML = data.hourly.map(x => `<article class="hour"><small>${time(x.time)}</small><b>${icon(x.condition)}</b><strong>${f(x.temperatureCelsius)}</strong><small>${x.precipitationProbability}% rain</small></article>`).join(''); $('daily').innerHTML = data.daily.map(x => `<article><small>${new Date(x.date + 'T12:00').toLocaleDateString('en-US',{weekday:'short'})}</small><div>${icon(x.condition)}</div><b>${f(x.maxCelsius)}</b><div class="range"></div><small>${f(x.minCelsius)} · ${x.precipitationProbability}%</small></article>`).join(''); drawChart(data.hourly); }
function drawChart(items) { const c = $('temp-chart'), ctx = c.getContext('2d'), width = c.width = c.clientWidth * devicePixelRatio, height = c.height = 220 * devicePixelRatio, values = items.map(x => x.temperatureCelsius); ctx.scale(devicePixelRatio, devicePixelRatio); const w = c.clientWidth, h = 220, min = Math.min(...values) - 2, max = Math.max(...values) + 2; ctx.clearRect(0,0,w,h); ctx.strokeStyle='#3d6683'; ctx.lineWidth=1; for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,i*h/4);ctx.lineTo(w,i*h/4);ctx.stroke()} ctx.beginPath(); values.forEach((v,i)=>{const x=i*w/(values.length-1),y=h-25-(v-min)/(max-min)*(h-45);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#67d8ff';ctx.lineWidth=3;ctx.stroke(); }
function renderAir(data) { $('aqi').textContent = data.aqi ?? '—'; $('aqi-category').textContent = data.category || 'Unavailable'; $('health-advice').textContent = data.aqi ? healthAdvice(data.aqi) : 'Air-quality data is currently unavailable.'; $('pollutants').innerHTML = Object.entries(data.pollutants).map(([k,v]) => `<article><small>${k.replace('pm','PM').toUpperCase()}</small><strong>${v == null ? '—' : `${Math.round(v)} µg/m³`}</strong></article>`).join(''); }
function renderAlerts(data) { $('alerts').innerHTML = !data.alerts.length ? '<p>No active National Weather Service alerts for this point.</p>' : data.alerts.map(a => `<article><b>${a.event || 'Weather alert'} · ${a.severity || 'Unknown severity'}</b><p>${a.headline || a.description || 'See local authorities for details.'}</p>${a.instruction ? `<small>${a.instruction}</small>` : ''}</article>`).join(''); }
async function loadWeather(query) { $('message').textContent = 'Refreshing live weather…'; try { const current = await request(`/api/weather/current?${query}`); renderCurrent(current); const q = `lat=${current.location.lat}&lon=${current.location.lon}`; const [forecast, air, alerts] = await Promise.all([request(`/api/weather/forecast?${q}`), request(`/api/weather/air-quality?${q}`), request(`/api/weather/alerts?${q}`).catch(e => ({ alerts: [], error: e.message }))]); renderForecast(forecast); renderAir(air); renderAlerts(alerts); updateMap(); $('message').textContent = 'Live data refreshed successfully.'; } catch (e) { $('message').textContent = e.message; } }
async function checkHealth() { try { const h = await request('/api/health-check'); $('backend-status').textContent = '🟢 Backend Status: Active | Render Cloud'; $('telemetry').textContent = `Operational · ${h.uptimeSeconds}s uptime · ${h.cacheEntries} cached locations · ${new Date(h.timestamp).toLocaleTimeString()}`; $('status-dot').style.color='#57dc82'; } catch (e) { $('backend-status').textContent = '🔴 Backend Status: Unavailable'; $('telemetry').textContent = e.message; $('status-dot').style.color='#ff6874'; } }
function updateMap() { if (!state.coords || !window.L) return; const lat = state.coords.lat, lon = state.coords.lon; if (!state.map) { state.map = L.map('map').setView([lat,lon],7); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(state.map); } else state.map.setView([lat,lon],7); if (state.overlay) state.map.removeLayer(state.overlay); state.overlay = L.tileLayer(`${API_BASE}/api/map/${state.layer}/{z}/{x}/{y}.png`,{opacity:.65}).addTo(state.map); }
document.querySelectorAll('.tab').forEach(b => b.onclick = () => { document.querySelectorAll('.tab,.panel').forEach(e => e.classList.remove('active')); b.classList.add('active'); $(b.dataset.tab).classList.add('active'); if (b.dataset.tab === 'radar') setTimeout(() => { if (state.map) state.map.invalidateSize(); updateMap(); }, 50); });
$('search-form').onsubmit = e => { e.preventDefault(); const city = $('search').value.trim(); if (city) { $('suggestions').style.display='none'; loadWeather(`q=${encodeURIComponent(city)}`); } };
let searchTimer; $('search').oninput = () => { clearTimeout(searchTimer); const q = $('search').value.trim(); if (q.length < 3) return $('suggestions').style.display='none'; searchTimer=setTimeout(async()=>{try{const list=await request(`/api/geo/search?q=${encodeURIComponent(q)}`); $('suggestions').innerHTML=list.map(x=>`<button data-lat="${x.lat}" data-lon="${x.lon}">${x.name}${x.state?`, ${x.state}`:''}, ${x.country}</button>`).join(''); $('suggestions').style.display=list.length?'block':'none'; document.querySelectorAll('#suggestions button').forEach(b=>b.onclick=()=>{ $('search').value=b.textContent; $('suggestions').style.display='none'; loadWeather(`lat=${b.dataset.lat}&lon=${b.dataset.lon}`); });}catch(e){}} ,250); };
$('locate').onclick = () => navigator.geolocation ? navigator.geolocation.getCurrentPosition(p => loadWeather(`lat=${p.coords.latitude}&lon=${p.coords.longitude}`), () => $('message').textContent='Location permission was not granted.') : $('message').textContent='Geolocation is not supported by this browser.';
$('units').onclick = () => { state.metric=!state.metric; $('units').textContent=state.metric?'°C · km/h':'°F · mph'; $('units-label').textContent=state.metric?'°C / km/h':'°F / mph'; if(state.coords) loadWeather(`lat=${state.coords.lat}&lon=${state.coords.lon}`); };
document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>{document.querySelectorAll('.layer').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.layer=b.dataset.layer;updateMap();});
window.addEventListener('load', () => { checkHealth(); loadWeather('q=New%20York'); });
