/** Production-ready weather API gateway. Node 18+ (native fetch). */
const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();
const startedAt = Date.now();
// Render injects PORT. Bind all interfaces so Render's reverse proxy can reach us.
const PORT = Number(process.env.PORT || 10000);
const HOST = process.env.HOST || '0.0.0.0';
const API_KEY = process.env.WEATHER_API_KEY || process.env.OPENWEATHER_API_KEY;
const BASE = 'https://api.openweathermap.org';
const allowedOrigins = (process.env.CORS_ORIGIN || '').split(',').map(s => s.trim()).filter(Boolean);
const cache = new Map();
const CACHE_TTL_MS = Number(process.env.CACHE_TTL_MS || 120000);
app.disable('x-powered-by');
app.use(cors({ origin(origin, done) { if (!origin || !allowedOrigins.length || allowedOrigins.includes(origin)) return done(null, true); return done(new Error('Origin is not allowed by CORS')); }, methods: ['GET', 'OPTIONS'], maxAge: 86400 }));
app.use(express.json({ limit: '32kb' }));
class ApiError extends Error { constructor(status, message) { super(message); this.status = status; } }
function number(value, fallback = null) { const n = Number(value); return Number.isFinite(n) ? n : fallback; }
function coordinates(req) { const lat = number(req.query.lat), lon = number(req.query.lon); return lat !== null && lon !== null && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180 ? { lat, lon } : null; }
async function upstream(apiPath) { if (!API_KEY) throw new ApiError(503, 'Weather service is not configured. Set WEATHER_API_KEY on the server.'); const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 8000); try { const response = await fetch(BASE + apiPath + (apiPath.includes('?') ? '&' : '?') + 'appid=' + encodeURIComponent(API_KEY), { signal: controller.signal }); const data = await response.json().catch(() => null); if (!response.ok) throw new ApiError(response.status === 404 ? 404 : 502, data?.message || 'Weather provider is temporarily unavailable.'); return data; } catch (error) { if (error instanceof ApiError) throw error; throw new ApiError(503, 'Weather provider did not respond. Please try again shortly.'); } finally { clearTimeout(timer); } }
async function cached(key, loader) { const item = cache.get(key), now = Date.now(); if (item && item.expiresAt > now) return { data: item.data, cached: true }; const data = await loader(); cache.set(key, { data, expiresAt: now + CACHE_TTL_MS }); if (cache.size > 250) cache.delete(cache.keys().next().value); return { data, cached: false }; }
function resolveQuery(req) { const coords = coordinates(req); if (coords) return { query: `lat=${coords.lat}&lon=${coords.lon}`, coords }; const q = String(req.query.q || '').trim(); if (!q || q.length > 120) throw new ApiError(400, 'Provide a valid city with ?q=City or coordinates with ?lat=&lon=.'); return { query: `q=${encodeURIComponent(q)}`, coords: null }; }
function direction(deg) { return ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'][Math.round((deg || 0) / 22.5) % 16]; }
function normalizeCurrent(raw) { return { location: { name: raw.name, country: raw.sys?.country, lat: raw.coord?.lat, lon: raw.coord?.lon, timezoneOffset: raw.timezone || 0 }, observedAt: new Date((raw.dt || Date.now() / 1000) * 1000).toISOString(), condition: { main: raw.weather?.[0]?.main || 'Unknown', description: raw.weather?.[0]?.description || 'Unavailable', icon: raw.weather?.[0]?.icon || '01d' }, temperature: { celsius: raw.main?.temp, feelsLikeCelsius: raw.main?.feels_like, minCelsius: raw.main?.temp_min, maxCelsius: raw.main?.temp_max }, humidity: raw.main?.humidity, pressureHpa: raw.main?.pressure, dewPointCelsius: raw.main?.temp != null && raw.main?.humidity != null ? Math.round((raw.main.temp - ((100 - raw.main.humidity) / 5)) * 10) / 10 : null, wind: { speedMps: raw.wind?.speed || 0, gustMps: raw.wind?.gust || null, directionDegrees: raw.wind?.deg || 0, direction: direction(raw.wind?.deg) }, visibilityMeters: raw.visibility ?? null, cloudCover: raw.clouds?.all ?? null, sun: { sunrise: raw.sys?.sunrise ? new Date(raw.sys.sunrise * 1000).toISOString() : null, sunset: raw.sys?.sunset ? new Date(raw.sys.sunset * 1000).toISOString() : null }, provider: 'OpenWeather' }; }
function normalizeForecast(raw) { const hourly = (raw.list || []).slice(0, 24).map(x => ({ time: new Date(x.dt * 1000).toISOString(), temperatureCelsius: x.main?.temp, feelsLikeCelsius: x.main?.feels_like, precipitationProbability: Math.round((x.pop || 0) * 100), humidity: x.main?.humidity, windMps: x.wind?.speed, condition: x.weather?.[0]?.description, icon: x.weather?.[0]?.icon })); const dailyMap = new Map(); for (const x of raw.list || []) { const day = new Date(x.dt * 1000).toISOString().slice(0,10), d = dailyMap.get(day) || { date: day, minCelsius: Infinity, maxCelsius: -Infinity, precipitationProbability: 0, samples: [] }; d.minCelsius = Math.min(d.minCelsius, x.main.temp_min); d.maxCelsius = Math.max(d.maxCelsius, x.main.temp_max); d.precipitationProbability = Math.max(d.precipitationProbability, Math.round((x.pop || 0) * 100)); d.samples.push(x); dailyMap.set(day, d); } return { location: raw.city ? { name: raw.city.name, country: raw.city.country, lat: raw.city.coord?.lat, lon: raw.city.coord?.lon } : null, hourly, daily: [...dailyMap.values()].slice(0, 7).map(d => { const s = d.samples[Math.floor(d.samples.length / 2)] || {}; return { date: d.date, minCelsius: d.minCelsius, maxCelsius: d.maxCelsius, precipitationProbability: d.precipitationProbability, condition: s.weather?.[0]?.description, icon: s.weather?.[0]?.icon }; }), provider: 'OpenWeather' }; }
function aqiLabel(aqi) { return ['Good', 'Fair', 'Moderate', 'Poor', 'Very Poor'][Math.max(0, Math.min(4, (aqi || 1) - 1))]; }
app.get('/api/health-check', (req, res) => res.status(200).json({ ok: true, status: 'operational', service: 'weather-api', uptimeSeconds: Math.floor((Date.now() - startedAt) / 1000), cacheEntries: cache.size, timestamp: new Date().toISOString() }));
app.get('/api/health', (req, res) => res.redirect(307, '/api/health-check'));
app.get('/api/weather/current', async (req, res, next) => { try { const { query } = resolveQuery(req), result = await cached(`current:${query}`, async () => normalizeCurrent(await upstream(`/data/2.5/weather?${query}&units=metric`))); res.set('X-Cache', result.cached ? 'HIT' : 'MISS').json(result.data); } catch (e) { next(e); } });
app.get('/api/weather/forecast', async (req, res, next) => { try { const { query } = resolveQuery(req), result = await cached(`forecast:${query}`, async () => normalizeForecast(await upstream(`/data/2.5/forecast?${query}&units=metric`))); res.set('X-Cache', result.cached ? 'HIT' : 'MISS').json(result.data); } catch (e) { next(e); } });
app.get('/api/weather/air-quality', async (req, res, next) => { try { let coords = coordinates(req); if (!coords) { const { query } = resolveQuery(req), current = await upstream(`/data/2.5/weather?${query}&units=metric`); coords = current.coord; } const result = await cached(`aq:${coords.lat},${coords.lon}`, async () => { const raw = await upstream(`/data/2.5/air_pollution?lat=${coords.lat}&lon=${coords.lon}`), row = raw.list?.[0] || {}; return { location: coords, observedAt: row.dt ? new Date(row.dt * 1000).toISOString() : new Date().toISOString(), aqi: row.main?.aqi || null, category: aqiLabel(row.main?.aqi), pollutants: { pm25: row.components?.pm2_5 ?? null, pm10: row.components?.pm10 ?? null, co: row.components?.co ?? null, no2: row.components?.no2 ?? null, o3: row.components?.o3 ?? null }, provider: 'OpenWeather' }; }); res.set('X-Cache', result.cached ? 'HIT' : 'MISS').json(result.data); } catch (e) { next(e); } });
app.get('/api/weather/alerts', async (req, res, next) => { try { const coords = coordinates(req); if (!coords) throw new ApiError(400, 'Alerts require ?lat=&lon=.'); const result = await cached(`alerts:${coords.lat},${coords.lon}`, async () => { const response = await fetch(`https://api.weather.gov/alerts/active?point=${coords.lat},${coords.lon}`, { headers: { 'User-Agent': 'WeatherClientDemo/1.0 contact@example.com', Accept: 'application/geo+json' } }); if (!response.ok) throw new ApiError(503, 'US alert service is temporarily unavailable.'); const raw = await response.json(); return { location: coords, alerts: (raw.features || []).map(f => ({ id: f.id, event: f.properties?.event, severity: f.properties?.severity, urgency: f.properties?.urgency, headline: f.properties?.headline, description: f.properties?.description, instruction: f.properties?.instruction, effective: f.properties?.effective, expires: f.properties?.expires })).slice(0, 20), provider: 'National Weather Service' }; }); res.set('X-Cache', result.cached ? 'HIT' : 'MISS').json(result.data); } catch (e) { next(e); } });
app.get('/api/map/:layer/:z/:x/:y.png', async (req, res, next) => { try { if (!['precipitation_new','wind_new','clouds_new','temp_new'].includes(req.params.layer)) throw new ApiError(400, 'Unsupported map layer.'); if (!API_KEY) throw new ApiError(503, 'Weather service is not configured.'); const url = `https://tile.openweathermap.org/map/${req.params.layer}/${req.params.z}/${req.params.x}/${req.params.y}.png?appid=${encodeURIComponent(API_KEY)}`; const response = await fetch(url); if (!response.ok) throw new ApiError(502, 'Map layer is temporarily unavailable.'); res.type('png').set('Cache-Control', 'public, max-age=300').send(Buffer.from(await response.arrayBuffer())); } catch (e) { next(e); } });
app.get('/api/geo/search', async (req, res, next) => { try { const q = String(req.query.q || '').trim(); if (!q) throw new ApiError(400, 'Provide a search query.'); const raw = await upstream(`/geo/1.0/direct?q=${encodeURIComponent(q)}&limit=6`); res.json(raw.map(x => ({ name: x.name, state: x.state, country: x.country, lat: x.lat, lon: x.lon }))); } catch (e) { next(e); } });
app.use(express.static(path.resolve(__dirname, '..'), { index: 'index.html', extensions: ['html'] }));
app.use((req, res) => res.status(404).json({ error: 'Route not found.', path: req.path }));
app.use((err, req, res, next) => { console.error(err.message); const status = err.status || 500; res.status(status).json({ error: status === 500 ? 'Unexpected server error.' : err.message, status, timestamp: new Date().toISOString() }); });
if (require.main === module) {
  const server = app.listen(PORT, HOST, () => console.log(`Weather API listening on http://${HOST}:${PORT}`));
  // Let Render drain in-flight requests during a deploy or restart.
  process.on('SIGTERM', () => server.close(() => process.exit(0)));
}
module.exports = app;
